### ISSUE TITLE
Moonrise/Moonset is missing

### ISSUE THREAD

**Issue by ucsbkn** [SanjayPrabhakaran/JyotishCalc#2]
Dear Sir,
Please add Moonrise/Moonset in excel sheet

**Comment by SanjayPrabhakaran** [comment]
Lot of work here will try

**Comment by ucsbkn** [comment]
this a very small job for you but for me, very important.

**Comment by SanjayPrabhakaran** [comment]
Moon Rise and Set has been added...

**Comment by SanjayPrabhakaran** [comment]
Done
