### ISSUE TITLE
Code needs update

### ISSUE THREAD

**Issue by sanjayrath** [SanjayPrabhakaran/JyotishCalc#3]
Code on this has to be updated to work on the 64-bit systems

Also can you make a page for all of chandra results like chandra-abhilasa etc

**Comment by SanjayPrabhakaran** [comment]
Namaste Guruji,
The code has been updated, I just modified the code for 64 Bit.
The 64 Bit DLL has has to be kept in the Documents Folder.- (Current Directory ([CurDir](https://learn.microsoft.com/en-us/office/vba/language/reference/user-interface-help/curdir-function) or PATH)
Else you will get a message indicating the expected location. 
Let me know if it works !

**Comment by SanjayPrabhakaran** [comment]
> Code on this has to be updated to work on the 64-bit systems
> 
> Also can you make a page for all of chandra results like chandra-abhilasa etc

Namaste Guruji,
How to calculate or provide any reference for chandra-abhilasa etc?
I will be eager to do it.
